[project]
name = "agent-book-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.32.0",
    "openai-agents>=0.14.3",
    "python-dotenv>=1.2.2",
    "textual>=8.2.4",
]

[project.scripts]
fh = "funharness.src.__main__:main"

[tool.setuptools.packages.find]
include = ["funharness*"]
